# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq/zynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_zynq_ultra_ps_e_0_0/zynq_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zynq_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_clk_wiz_0_0/zynq_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_clk_wiz_0_0 || ORIG_REF_NAME==zynq_clk_wiz_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_proc_sys_reset_0_1/zynq_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_0_1 || ORIG_REF_NAME==zynq_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_proc_sys_reset_1_0/zynq_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_1_0 || ORIG_REF_NAME==zynq_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_proc_sys_reset_2_0/zynq_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_2_0 || ORIG_REF_NAME==zynq_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_intc_0_0/zynq_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_axi_intc_0_0 || ORIG_REF_NAME==zynq_axi_intc_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_auto_pc_0 || ORIG_REF_NAME==zynq_auto_pc_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps8_0_axi_periph_0/zynq_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps8_0_axi_periph_0 || ORIG_REF_NAME==zynq_ps8_0_axi_periph_0} -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_zynq_ultra_ps_e_0_0/zynq_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_zynq_ultra_ps_e_0_0/zynq_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zynq_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_clk_wiz_0_0/zynq_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_clk_wiz_0_0 || ORIG_REF_NAME==zynq_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_clk_wiz_0_0/zynq_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_clk_wiz_0_0 || ORIG_REF_NAME==zynq_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_clk_wiz_0_0/zynq_clk_wiz_0_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_proc_sys_reset_0_1/zynq_proc_sys_reset_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_0_1 || ORIG_REF_NAME==zynq_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_proc_sys_reset_0_1/zynq_proc_sys_reset_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_0_1 || ORIG_REF_NAME==zynq_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_proc_sys_reset_1_0/zynq_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_1_0 || ORIG_REF_NAME==zynq_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_proc_sys_reset_1_0/zynq_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_1_0 || ORIG_REF_NAME==zynq_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_proc_sys_reset_2_0/zynq_proc_sys_reset_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_2_0 || ORIG_REF_NAME==zynq_proc_sys_reset_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_proc_sys_reset_2_0/zynq_proc_sys_reset_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_proc_sys_reset_2_0 || ORIG_REF_NAME==zynq_proc_sys_reset_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_axi_intc_0_0/zynq_axi_intc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_axi_intc_0_0 || ORIG_REF_NAME==zynq_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_axi_intc_0_0/zynq_axi_intc_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_axi_intc_0_0 || ORIG_REF_NAME==zynq_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_axi_intc_0_0/zynq_axi_intc_0_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0_ooc.xdc

# XDC: c:/altera/13.1/MSIB/vivado/projectFPGA/projectFPGA.gen/sources_1/bd/zynq/zynq_ooc.xdc
